# Generated by Django 3.2.12 on 2022-04-04 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=64, unique=True)),
                ('extra_facilities', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('height', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('length', models.PositiveSmallIntegerField()),
                ('weight_capacity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('company_code', models.CharField(max_length=64, unique=True)),
                ('support_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('CP', 'complete'), ('IP', 'in-progress'), ('BL', 'backlog'), ('MS', 'missed')], default='BL', max_length=2)),
                ('weight', models.PositiveIntegerField()),
                ('start_tw', models.DateTimeField()),
                ('end_tw', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=models.SET('deleted'), related_name='orders_set', to='haul.car')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('store_code', models.CharField(max_length=64, unique=True)),
                ('longtitude', models.PositiveIntegerField(default=0)),
                ('latitude', models.PositiveIntegerField(default=0)),
                ('owner_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('longtitude', models.PositiveIntegerField(default=0)),
                ('latitude', models.PositiveIntegerField(default=0)),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages_set', to='haul.company')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtitude', models.PositiveIntegerField(default=0)),
                ('latitude', models.PositiveIntegerField(default=0)),
                ('current_datetime', models.DateTimeField()),
                ('action', models.CharField(choices=[('ST', 'started-trip'), ('ED', 'ended-trip'), ('OW', 'on-the-way'), ('TB', 'taking-break'), ('DV', 'delivered'), ('CH', 'charging'), ('DC', 'discharging')], default='ST', max_length=2)),
                ('related_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_set', to='haul.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_set', to='haul.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_set', to='haul.storage'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers_set', to='haul.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_set', to='haul.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_set', to='haul.company'),
        ),
    ]
