# Generated by Django 3.2.12 on 2022-04-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haul', '0002_auto_20220410_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimation_end',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimation_start',
        ),
        migrations.AddField(
            model_name='order',
            name='estimation_arrival',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimation_depart',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='estimationfiles',
            name='orders',
            field=models.FileField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='estimationfiles',
            name='routes',
            field=models.FileField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted'), related_name='orders_set', to='haul.car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_set', to='haul.store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_tw',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_set', to='haul.storage'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_tw',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
