# Generated by Django 3.2.12 on 2022-04-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haul', '0003_auto_20220410_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=models.SET('deleted'), related_name='orders_set', to='haul.driver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AS', 'assigned'), ('IP', 'in-progress'), ('AR', 'arrived'), ('DL', 'delivered')], default='AS', max_length=2),
        ),
    ]
