# Generated by Django 3.2.12 on 2022-04-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haul', '0004_auto_20220410_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlog',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='pathestimation',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='estimationfiles',
            name='orders',
            field=models.FileField(upload_to='static/2022-04-11 18:57:43.648449'),
        ),
        migrations.AlterField(
            model_name='estimationfiles',
            name='routes',
            field=models.FileField(upload_to='static/2022-04-11 18:57:43.648449'),
        ),
    ]
