# Generated by Django 3.2.12 on 2022-04-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haul', '0005_auto_20220411_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationfiles',
            name='depot',
            field=models.FileField(null=True, upload_to='static/2022-04-12 16:48:35.976982'),
        ),
        migrations.AddField(
            model_name='estimationfiles',
            name='depot_visit',
            field=models.FileField(null=True, upload_to='static/2022-04-12 16:48:35.976982'),
        ),
        migrations.AlterField(
            model_name='estimationfiles',
            name='orders',
            field=models.FileField(upload_to='static/2022-04-12 16:48:35.976982'),
        ),
        migrations.AlterField(
            model_name='estimationfiles',
            name='routes',
            field=models.FileField(upload_to='static/2022-04-12 16:48:35.976982'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders_set', to='haul.driver'),
        ),
    ]
