# Generated by Django 3.2.12 on 2022-04-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haul', '0006_auto_20220412_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationfiles',
            name='depot',
            field=models.FileField(null=True, upload_to='static/2022-04-12 16:53:15.364383'),
        ),
        migrations.AlterField(
            model_name='estimationfiles',
            name='depot_visit',
            field=models.FileField(null=True, upload_to='static/2022-04-12 16:53:15.364383'),
        ),
        migrations.AlterField(
            model_name='estimationfiles',
            name='orders',
            field=models.FileField(upload_to='static/2022-04-12 16:53:15.364383'),
        ),
        migrations.AlterField(
            model_name='estimationfiles',
            name='routes',
            field=models.FileField(upload_to='static/2022-04-12 16:53:15.364383'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
