# Generated by Django 3.2.12 on 2022-04-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haul', '0006_auto_20220412_1705'),
        ('haul', '0007_auto_20220412_1653'),
    ]

    operations = [
    ]
