# Generated by Django 3.2.12 on 2022-04-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haul', '0008_merge_0006_auto_20220412_1705_0007_auto_20220412_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationfiles',
            name='depot',
            field=models.FileField(null=True, upload_to='static/<django.db.models.fields.DateTimeField>'),
        ),
        migrations.AlterField(
            model_name='estimationfiles',
            name='depot_visit',
            field=models.FileField(null=True, upload_to='static/<django.db.models.fields.DateTimeField>'),
        ),
        migrations.AlterField(
            model_name='estimationfiles',
            name='orders',
            field=models.FileField(upload_to='static/<django.db.models.fields.DateTimeField>'),
        ),
        migrations.AlterField(
            model_name='estimationfiles',
            name='routes',
            field=models.FileField(upload_to='static/<django.db.models.fields.DateTimeField>'),
        ),
    ]
